# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1226, 787)
        MainWindow.setStyleSheet("#ip_address , #port , #start{font-size: 28px;}\n"
"#er_sv , #list_client , #list_file{font-size: 21px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 0, 161, 91))
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(140, 470, 171, 71))
        self.start.setObjectName("start")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 141, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 230, 141, 51))
        self.label_3.setObjectName("label_3")
        self.ip_address = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_address.setGeometry(QtCore.QRect(90, 170, 221, 31))
        self.ip_address.setText("")
        self.ip_address.setObjectName("ip_address")
        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(90, 280, 221, 31))
        self.port.setText("")
        self.port.setObjectName("port")
        self.list_client = QtWidgets.QListWidget(self.centralwidget)
        self.list_client.setGeometry(QtCore.QRect(420, 120, 391, 571))
        self.list_client.setObjectName("list_client")
        self.list_file = QtWidgets.QListWidget(self.centralwidget)
        self.list_file.setGeometry(QtCore.QRect(850, 120, 291, 571))
        self.list_file.setObjectName("list_file")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(475, 90, 131, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(850, 90, 131, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(990, 0, 231, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 620, 331, 111))
        self.label_7.setObjectName("label_7")
        self.abc = QtWidgets.QLineEdit(self.centralwidget)
        self.abc.setGeometry(QtCore.QRect(50, 380, 341, 31))
        self.abc.setText("")
        self.abc.setObjectName("abc")
        self.auto_2 = QtWidgets.QPushButton(self.centralwidget)
        self.auto_2.setGeometry(QtCore.QRect(322, 170, 91, 31))
        self.auto_2.setObjectName("auto_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt;\">SERVER</span></p></body></html>"))
        self.start.setText(_translate("MainWindow", "START"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">IP ADDRESS:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">PORT:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">list client:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">list file:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">dev: Ng Trong Tuan</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">báo cáo lỗi</span><span style=\" font-size:14pt;\">: </span></p><p><span style=\" font-size:12pt;\">gmail: trongtuan150409@gmail.com</span></p><p><span style=\" font-size:12pt;\">zalo: 0862.113.464</span></p></body></html>"))
        self.auto_2.setText(_translate("MainWindow", "Tự động điền"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
